#pragma once
#include <iostream>
#define MAX_NAME_LENGTH 255
#define NUMBER_OF_OCEAN_PIECES 6
#define NUMBER_OF_HABITATS 6
#define NUMBER_OF_RESOURCES 5
#define HEX_COUNT 19
#define RESOURCES_STR "LMNOPT"
#define POINTS_TO_WIN 8
#define OFFSET_CARD_X 149
#define OFFSET_CARD_Y 189
#define OFFSET_YES_X 80
#define OFFSET_YES_Y 80
#define OFFSET_NO_X 80
#define OFFSET_NO_Y 80
#define OFFSET_END_TURN_X 200
#define OFFSET_END_TURN_Y 89
#define OFFSET_BANK_TRADE_X 90
#define OFFSET_BANK_TRADE_Y 64
#define OFFSET_PLAYER_TURN_X 90
#define OFFSET_PLAYER_TURN_Y 79
#define OFFSET_EXIT_X 80
#define OFFSET_EXIT_Y 80

typedef enum resourceType { BRICK = 'L', WOOD, DESSERT, WOOL, ORE, WHEAT = 'T'};

